name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-validate:
    name: Lint & Validate
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dev dependencies
        run: |
          pip install --upgrade pip
          pip install black isort flake8 mypy homeassistant

      #- name: Black formatting check
      #  run: black --check .

      - name: isort import sort check
        run: isort --check-only .

      - name: Flake8 lint
        run: flake8 .

      - name: Mypy type check
        run: mypy .

      - name: Home Assistant manifest validation (hassfest)
        run: |
          # hassfest checks manifest.json, config_flow, etc.
          hassfest .
